name = "SimpleCTF"
uuid = "591e75a0-d7a3-4ba8-957d-6fc0b9f2e874"
authors = ["Albert Xu <albert.t.xu@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
